version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=diary

  web:
    build: .
    environment:
      - DBNAME=diary
      - DBUSER=root
      - DBPASSWORD=123456
      - DBHOST=db
      - DBPORT=3306
    volumes:
      - .:/site/
    ports:
      - "8000:8000"
    depends_on:
      - db
    