# Generated by Django 4.0.6 on 2022-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_diary_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='diary',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
